version: "2"

volumes:
   db-data:
    external: false

services:
  db:
    image: sqlite3-client
    env_file: .env
    volumes:
      - db-data:/var/lib/sqlite3/db-data


app:
  build: .
  env_file: .env
  volumes:
    - .:/usr/src/app
  ports:
    - "3000:3000"
  depends_on:
    - db